### ISSUE TITLE
lxml causes 600% build time increase, find alternative and implement.

### ISSUE THREAD

**Issue by System-Flenser** [TheInnerCircleO/icbot#17]
![1327252959_youhaveten](https://cloud.githubusercontent.com/assets/11688898/7092287/42904634-df65-11e4-92d4-b55552cbce0b.jpg)

**Comment by PHLAK** [comment]
Possible alternative: https://docs.python.org/2/library/xml.etree.elementtree.html

**Comment by uberscientist** [comment]
It is done
